### ISSUE TITLE
Redundant relativization

### ISSUE THREAD

**Issue by fcbr** [own-pt/cl-krr#1]
This formula:

``` Lisp
(=>
   (exhaustiveDecomposition ?CLASS ?ROW0 ?ROW1)
   (and (instance ?CLASS Class) 
        (instance ?ROW0 Class) 
        (instance ?ROW1 Class)))
```

was relativized as:

``` Lisp
(forall (?CLASS ?ROW1 ?ROW0)
 (=>
  (and (instance ?ROW0 Entity) (instance ?ROW0 Class)
       (instance ?ROW1 Entity) (instance ?ROW1 Class)
       (instance ?CLASS Class) (instance ?CLASS Entity))
  (=> (exhaustiveDecomposition3 ?CLASS ?ROW0 ?ROW1)
   (and (instance ?CLASS Class)
        (and (instance ?ROW0 Class) (instance ?ROW1 Class))))))
```

Which is clearly wrong: the purpose of the formula is to instantiate `?CLASS`, `?ROW0`, and `?ROW1` as instances of `Class`, so they can't be added as restrictions in the antecedent.

**Comment by arademaker** [comment]
Can we generalize it so all (instance ...) in the conclusion of the rules should not contribute to types restrictions ?

**Comment by fcbr** [comment]
Yes, that's the idea.

**Comment by arademaker** [comment]
OK, but I don't like the idea to have implications as special constructor since they are only one more ordinary logical constructor

**Comment by arademaker** [comment]
Close in favor of #24. Same issue.
