### ISSUE TITLE
equal 

### ISSUE THREAD

**Issue by arademaker** [own-pt/cl-krr#20]
FOF understand the `=` operator. We need to transform the `equal` from SUMO to the `=` predefined operator in FOF and TFF. Moreover, equal is not well defined in SUMO. 

http://localhost:8080/sigma/Browse.jsp?kb=SUMO&lang=EnglishLanguage&flang=SUO-KIF&term=equal

I couldn't prove `(equal Animal Animal)`!

**Comment by arademaker** [comment]
true => $true
false => $false

**Comment by fcbr** [comment]
https://github.com/own-pt/cl-krr/blob/master/tptp.lisp#L23

**Comment by arademaker** [comment]
Hum, so why equals are not replaced by the equality symbol?

**Comment by hmuniz** [comment]
It's missing `|equal|` in `*binary-logical-operators*` definition.
https://github.com/own-pt/cl-krr/blob/b5b6228b31a39fcacc59293d647cb5781f63110c/utils.lisp#L39

**Comment by hmuniz** [comment]
@arademaker  is it solved?

**Comment by arademaker** [comment]
I have also changed the `binary-logical-formulap` function using another approach.

**Comment by hmuniz** [comment]
Actually, I should not have added `equal` to `*binary-logical-operators*`, your approach is the correct one. I am going to fix this.

**Comment by arademaker** [comment]
Yes. It is better. Ok , I will wait your fix

**Comment by hmuniz** [comment]
It's done.
